name: Linux Build

on: push

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: c4c66386f47053694afcbab6e1eba4bfb3fcd729

    - name: Build HandBrake Linux
      run: |
         make
